version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper 
    ports:
      - 2181:2181   
    networks:
      - aioip_net         
  kafka:
    image: wurstmeister/kafka     
    volumes: 
      - /etc/localtime:/etc/localtime 
    ports:
      - 9092:9092
    environment: 
      KAFKA ADVERTISED HOST NAME: localhost
      KAFKA ZOOKEEPER CONNECT: zookeeper:2181 
    networks:
      - aioip_net
  kafka-manager: 
    image: sheepkiller/kafka-manager
    environment: 
      ZK_HOSTS: "127.0.0.1"
    ports: 
      - "9000:9000"
    networks:
      - aioip_net
  redis:
    image: redis:5.0-rc3
    volumes:
      - /data/redis/data:/data
    ports:
      - 6379:6379
    networks:
      - aioip_net
  mongo:
    image: mongo
    volumes:
      - /home/volumes/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - aioip_net
networks:
  aioip_net:
    driver: overlay
